In [1]:
import tensorflow as tf

In [4]:
  print(tf.__version__)

  # Create Tensor
  tensor1 = tf.range(5)
  
  #print(dir(tf.data.Dataset))
  #Create dataset, this will return object of TensorSliceDataset
  dataset = tf.data.Dataset.from_tensor_slices(tensor1)
  print(dataset)
  print("Original dataset")
  for i in dataset:    
      print(i)
      #print(i.numpy())

  dataset = dataset.batch(batch_size=2)
  print("dataset after applying batch method")
  for i in dataset:
      print(i)
    
  print("\ndataset after applying take() method")
  for i in dataset.take(4):
        print(i)

2.3.0
<TensorSliceDataset shapes: (), types: tf.int32>
Original dataset
tf.Tensor(0, shape=(), dtype=int32)
0
tf.Tensor(1, shape=(), dtype=int32)
1
tf.Tensor(2, shape=(), dtype=int32)
2
tf.Tensor(3, shape=(), dtype=int32)
3
tf.Tensor(4, shape=(), dtype=int32)
4
dataset after applying batch method
tf.Tensor([0 1], shape=(2,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor([4], shape=(1,), dtype=int32)

dataset after applying take() method
tf.Tensor([0 1], shape=(2,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor([4], shape=(1,), dtype=int32)


In [8]:
# numpy to dataset
ds = tf.data.Dataset.from_tensor_slices([[5, 10], [3, 6]])
  
# dataset elements as tensors
for e in ds:
    print(e)
    
# dataset to numpy
for e in ds:
    print(e.numpy())

tf.Tensor([ 5 10], shape=(2,), dtype=int32)
tf.Tensor([3 6], shape=(2,), dtype=int32)
[ 5 10]
[3 6]


In [8]:
# Create Tensor
tensor1 = tf.range(6)

In [9]:
#print(dir(tf.data.Dataset))
#Create dataset, this will return object of TensorSliceDataset
dataset = tf.data.Dataset.from_tensor_slices(tensor1)
print(dataset)
print("Original dataset")
for i in dataset:    
    print(i)

<TensorSliceDataset shapes: (), types: tf.int32>
Original dataset
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [10]:
#Using batch method with repeat
dataset = dataset.repeat(3).batch(batch_size=2)
print("\ndataset after applying batch method with repeat()")
for i in dataset:
    print(i)


dataset after applying batch method with repeat()
tf.Tensor([0 1], shape=(2,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor([4 5], shape=(2,), dtype=int32)
tf.Tensor([0 1], shape=(2,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor([4 5], shape=(2,), dtype=int32)
tf.Tensor([0 1], shape=(2,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor([4 5], shape=(2,), dtype=int32)


In [11]:
print("dataset after applying take() method")
for i in dataset.take(4):
  print(i)

dataset after applying take() method
tf.Tensor([0 1], shape=(2,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor([4 5], shape=(2,), dtype=int32)
tf.Tensor([0 1], shape=(2,), dtype=int32)


In [12]:
# Transforming dataset items using map()
print("dataset after applying map function")
dataset = dataset.map(lambda x : x*x*x)
for i in dataset:
    print(i)

dataset after applying map function
tf.Tensor([0 1], shape=(2,), dtype=int32)
tf.Tensor([ 8 27], shape=(2,), dtype=int32)
tf.Tensor([ 64 125], shape=(2,), dtype=int32)
tf.Tensor([0 1], shape=(2,), dtype=int32)
tf.Tensor([ 8 27], shape=(2,), dtype=int32)
tf.Tensor([ 64 125], shape=(2,), dtype=int32)
tf.Tensor([0 1], shape=(2,), dtype=int32)
tf.Tensor([ 8 27], shape=(2,), dtype=int32)
tf.Tensor([ 64 125], shape=(2,), dtype=int32)


note 8, 27, etc

In [ ]:
# Playing 52 deck cards
tensor1 = tf.range(52)
dataset = tf.data.Dataset.from_tensor_slices(tensor1)
print(dataset)
print("Original dataset")
#for i in dataset:    
    #print(i)

In [ ]:
#Using batch method with repeat
dataset = dataset.shuffle(52).batch(4)

In [8]:
for i in dataset:    
    print(i)

<TensorSliceDataset shapes: (), types: tf.int32>
Original dataset
tf.Tensor([ 3 36 51 40], shape=(4,), dtype=int32)
tf.Tensor([30  4  8 13], shape=(4,), dtype=int32)
tf.Tensor([44  0  9 47], shape=(4,), dtype=int32)
tf.Tensor([41  1 10 45], shape=(4,), dtype=int32)
tf.Tensor([49 23 34 18], shape=(4,), dtype=int32)
tf.Tensor([ 6 17 28  2], shape=(4,), dtype=int32)
tf.Tensor([12 26 37 50], shape=(4,), dtype=int32)
tf.Tensor([22 31 15 21], shape=(4,), dtype=int32)
tf.Tensor([25 24 39 14], shape=(4,), dtype=int32)
tf.Tensor([11 33 20 29], shape=(4,), dtype=int32)
tf.Tensor([ 5 48 38 16], shape=(4,), dtype=int32)
tf.Tensor([35 19 46 27], shape=(4,), dtype=int32)
tf.Tensor([32 42  7 43], shape=(4,), dtype=int32)


In [ ]:
# Playing Ludo
tensor1 = tf.range(6)
dataset = tf.data.Dataset.from_tensor_slices(tensor1)
print(dataset)
print("Original dataset")
#for i in dataset:    
    #print(i)

In [ ]:
#Using batch method with repeat
dataset = dataset.shuffle(1)

In [18]:
for i in dataset:    
    print(i)

<TensorSliceDataset shapes: (), types: tf.int32>
Original dataset
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
----
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
----
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
print("----")
dataset = dataset.shuffle(2)

In [ ]:
for i in dataset:    
    print(i)    

In [ ]:
print("----")
dataset = dataset.shuffle(3)

In [ ]:
for i in dataset:    
    print(i)  